version: "1.2"
description: Sordum's Mouse Settings Changer
homepage: https://www.sordum.org/13237/
license:
  identifier: Freeware
  url: https://www.sordum.org/eula/
url: https://www.sordum.org/files/download/mouse-settings-changer/MouseSC.zip
hash: a7f18aa6a0f55349423f05a378769634394dc81cc7bbc9d9681a96f030b76a61
extract_dir: MouseSC
architecture:
  64bit:
    bin:
    - MouseSC_x64.exe
    - - MouseSC_x64.exe
      - MouseSC
  32bit:
    bin: MouseSC.exe
checkver: v([\d.]+)
autoupdate:
  url: https://www.sordum.org/files/download/mouse-settings-changer/MouseSC.zip
