version: "0"
description: Sordum's Mouse Settings Changer
homepage: https://www.sordum.org/13237/
license:
  identifier: Freeware
  url: https://www.sordum.org/eula/
url: https://www.sordum.org/files/download/mouse-settings-changer/MouseSC.zip
hash: 27c0f7a0612aee1e7759c94f92f5de8968883efc0269536c9d8c145a0f9b30af
extract_dir: MouseSC
architecture:
  64bit:
    bin:
    - MouseSC_x64.exe
    - - MouseSC_x64.exe
      - MouseSC
  32bit:
    bin: MouseSC.exe
checkver: v([\d.]+)
autoupdate:
  url: https://www.sordum.org/files/download/mouse-settings-changer/MouseSC.zip
